### ISSUE TITLE
Development of Basic Version With ROBOT Resources

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/Phaleron-SkeletalInventory#1]
This is to provide off-repository preparations by @cuboideum for further development. There are some tabular-separated value files for class generation with the [ROBOT](https://robot.obolibrary.org/) function [template](https://robot.obolibrary.org/template) along with scripts to use them.

GitHub does not support the types of files that are provided here. They are, therefore, all contained in the following archive:

[PhaleronSI-ROBOTResources.zip](https://github.com/RDFBones/Phaleron-SkeletalInventory/files/6847787/PhaleronSI-ROBOTResources.zip)

What the individual files contain and what they do is documented below. This documentation outlines a process pipeline.  Scripts need to be executed in this order because some of them require the output of previous scripts as input.

As agreed in the RDFBones/AnthroGraph meeting on 19 July 2021, I have also included the current output of the scripts (see OWL files). An overview of what is left to do is provided at the bottom.

# Basic Resources

## RDFBonesCore-StandardsSI.owl   
Graph containing a snapshot of the RDFBones core ontology and the Standards-SkeletalInventory extension. The file is needed as input for ROBOT template scripts.

# Class Creation

## Category Labels

**Template_CategoryLabels.tsv**   
Input table for ROBOT template function.

**Command_CreateCategoryLabels.sh**   
Bash script for the creation of category labels.

**Created_CategoryLabels.owl**   
Output of bash script.

## Value Specifications

**Template_ValueSpecifications.tsv**   
Input table for ROBOT template function.
y section
**Command_CreateValueSpecifications.sh**   
Bash script for the creation of value specification classes. It creates the file 'Merged_CategoryLabels.owl' that is needed as input in order to satisfy Manchester syntax requirements.

**Created_ValueSpecifications.sh**
Output of bash script.

## Anatomical Regions of Interest

**Template_AnatomicalROIs.tsv**   Wrap Up
Input table for ROBOT template function.

**Command_CreateAnatomicalROIs.sh**
Bash script for the creation of anatomical ROI calsses. It requires the file 'RDFBones-StandardsSI.owl' as input in order to satisfy Manchester Syntax requirements.

**Created_AnatomicalROIs.owl**   
Output of bash script.

## Measurement Data

**Template_MeasurementData.tsv**   
Input table for ROBOT template function.

**Command_CreateMeasurementData.sh**   
Bash script for the creation of measurement datum classes. It creates the file 'Merged_ValueSpecifications.owl' that is needed as input in order to satisfy Manchester syntax requirements.

**Created_MeasurementData.owl**   
Output of bash script.

## Skeletal Inventory Sections

**Template_SkeletalInventorySections.tsv**   
Input table for ROBOT template function.

**Command_CreateSkeletalInventorySections.sh**  
Bash script for the creation of skeletal inventory section classes. It creates the file 'Merged_MeasurementData.owl' that is needed as input in order to satisfy Manchester syntax requirements.

**Created_SkeletalInventorySections.owl**   
Output of bash script.

## Skeletal Inventories

**Template_SkeletalInventories.tsv**   
Input table for ROBOT template function.

**Command_CreateSkeletalInventories.sh**   
Bash script for the creation of skeletal inventory classes. It creates the file 'Merged_SkeletalInventorySections.owl' that is needed as input in order to satisfy Manchester syntax requirements.

**Created_SkeletalInventories.owl**   
Output of bash script.

# Basic Version

**Command_MergePhaleronSIComponents.sh**   
Bash script for compiling the basic version of the extension from the components created above.

**Merged_phaleron-si.owl**   
Output of bash script.

# To Do

The following work is still to be done:

* Finish skeletal inventory sections template
     * Create all sections
     * Add regions of interest to restrictions on measurement data counting unsided elements
* Finish skeletal inventory template
     * Add restrictions defining skeletal inventory sections
* Finalise basic version of extension
     * Compile basic version from components (cf. script above)
     * Fix bugs

**Comment by 15E601** [comment]
Basic version released.
