### ISSUE TITLE
Class SegmentOfClavicle

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/Phaleron-SkeletalInventory#11]
File [phaleron-si.owl](https://github.com/RDFBones/Phaleron-SkeletalInventory/blob/main/phaleron-si.owl) references the class SegmentOfClavicle from the [Standards Skeletal Inventories module](https://github.com/RDFBones/Standards-SkeletalInventories):

`<owl:Class rdf:about="http://w3id.org/rdfbones/ext/standards-si/SegmentOfClavicle"/>`

The Standards Skeletal Inventories module, however, does not contain this class and it would be unnecessary there as the Standards only inventory clavicles on the level of right or left entire bone organs.

So SegmentOfClavicle should be defined in phaleron-si.owl. The following changes are required:

1. Add a full class definition for phaleron-si:SegmentOfClavicle
2. Change namespace references from standards-si:SegmentOfClavicle to phaleron-si:SegmentOfClavicle

**Comment by 15E601** [comment]
Fixed. Will be implemented with the next iteration of the ontology.

**Comment by cuboideum** [comment]
The implementation has not yet reached the main branch.
