### ISSUE TITLE
Anatomical ROIs of pubic symphysis

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/Phaleron-SkeletalInventory#12]
In file [phaleron-si.owl], the anatomical regions of interest phaleron-si:LeftPubicSymphysis and phaleron-si:RightPubicSymphysis are defined as regional parts of fma:fma16950 ('Pubic symphysis'):

```
<owl:Class rdf:about="http://w3id.org/rdfbones/ext/phaleron-si/LeftPubicSymphysis">
        <rdfs:subClassOf rdf:resource="http://w3id.org/rdfbones/ext/phaleron-si/PubicSymphysis"/>
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://purl.org/sig/ont/fma/regional_part_of"/>
                <owl:allValuesFrom rdf:resource="http://purl.org/sig/ont/fma/fma16950"/>
            </owl:Restriction>
        </rdfs:subClassOf>
        <rdfs:label xml:lang="en">Left pubic symphysis</rdfs:label>
    </owl:Class>
```
```
<owl:Class rdf:about="http://w3id.org/rdfbones/ext/phaleron-si/RightPubicSymphysis">
        <rdfs:subClassOf rdf:resource="http://w3id.org/rdfbones/ext/phaleron-si/PubicSymphysis"/>
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://purl.org/sig/ont/fma/regional_part_of"/>
                <owl:allValuesFrom rdf:resource="http://purl.org/sig/ont/fma/fma16950"/>
            </owl:Restriction>
        </rdfs:subClassOf>
        <rdfs:label xml:lang="en">Right pubic symphysis</rdfs:label>
    </owl:Class>
```
While it is correct that the anatomical ROIs are regional parts of the pubic symphysis, in RDFBones, segments of bone organs (subclasses of rdfbones:SegmentOfBoneOrgan) should be defined as regional parts of bone organs. This is to ensure that all observations can be aggregated on the level of entire bone organs. So the range classes should be fma:fma16587 ('Left hip bone') and fma:fma16586 ('Right hip bone').

It might be a good idea to define ROIs also as regional parts of anatomical entities below the level of bone organs. This should be discussed in an RDFBones/AnthroGraph workgroup meeting.

**Comment by 15E601** [comment]
Left surface is now defined as regional part of fma16587, right surface is regional part of fma16586. See also #14
