### ISSUE TITLE
Unknown class IAO_0000938

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/Phaleron-SkeletalInventory#13]
The file file [phaleron-si.ow.](https://github.com/RDFBones/Phaleron-SkeletalInventory/blob/main/phaleron-si.owl) defines the classes phaleron-si:OnehundredElementsAssessment and phaleron-si:FiftyElementsAssessment as subclasses of class obo:IAO_0000938:

```
    <owl:Class rdf:about="http://w3id.org/rdfbones/ext/phaleron-si/FiftyElementsAssessment">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/IAO_0000938"/>
        <rdfs:subClassOf>
        <rdfs:label xml:lang="en">Degree of skull fragmentation</rdfs:label>
    </owl:Class>

```
```
    <owl:Class rdf:about="http://w3id.org/rdfbones/ext/phaleron-si/OnehundredElementsAssessment">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/IAO_0000938"/>
        <rdfs:subClassOf>
        <rdfs:label xml:lang="en">Degree of skeleton fragmentation</rdfs:label>
    </owl:Class>
```

The class obo:IAO_0000938 does not seem to exist. Most likely, the classes should be subclasses of obo:OBI_0000938 ('categorical measurement datum') and the problem was caused by a typo.

If so, the class references need to be changed.

**Comment by 15E601** [comment]
Yes, I appear to have confused obo:IAO_0000109 with obo:OBI_0000938.
phaleron-si:NumberOfBoneFragments was also affected. The typo in the template has been corrected and the fix will be in the next iteration of the phaleron ontology.
