### ISSUE TITLE
Naming of symphyseal surfaces

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/Phaleron-SkeletalInventory#14]
File [phaleron-si.owl](https://github.com/RDFBones/Phaleron-SkeletalInventory/blob/main/phaleron-si.owl) defines three anatomical regions of interest referring to pubic symphyses:

```
    <owl:Class rdf:about="http://w3id.org/rdfbones/ext/phaleron-si/PubicSymphysis">
        <rdfs:subClassOf rdf:resource="http://w3id.org/rdfbones/ext/standards-si/SegmentOfHipBone"/>
        <rdfs:label xml:lang="en">Pubic symphysis</rdfs:label>
    </owl:Class>
```

```
    <owl:Class rdf:about="http://w3id.org/rdfbones/ext/phaleron-si/LeftPubicSymphysis">
        <rdfs:subClassOf rdf:resource="http://w3id.org/rdfbones/ext/phaleron-si/PubicSymphysis"/>
        <rdfs:subClassOf>
        <rdfs:label xml:lang="en">Left pubic symphysis</rdfs:label>
    </owl:Class>
```

```
    <owl:Class rdf:about="http://w3id.org/rdfbones/ext/phaleron-si/RightPubicSymphysis">
        <rdfs:subClassOf rdf:resource="http://w3id.org/rdfbones/ext/phaleron-si/PubicSymphysis"/>
        <rdfs:subClassOf>
        <rdfs:label xml:lang="en">Right pubic symphysis</rdfs:label>
    </owl:Class>
```

It should be noted that there is only one pubic symphysis in the human skeleton which mostly consists of cartilage tissue.
What is actually scored are the symphyseal surfaces of the left and right pubic bones.

The following names would be more correct:

* phaleron-si:SymphysialSurfaceOfPubis (label: Symphysial surface of pubis, note: describes the same as class fma:fma16965 'Symphysial surface of pubis')
* phaleron-si:LeftSymphysialSurfaceOfPubis (label: Left symphysial surface of pubis)
* phaleron-si:RightSymphysialSurfaceOfPubis (label: Right symphysial surface of pubis)

In any case, changes to the class labels would be desirable. As we are still pre-release, changing the URIs is also feasible.

**Comment by JEB13** [comment]
Correct -- syphysis is joint.  But it is "symphyseal" not "symphysial".

**Comment by 15E601** [comment]
Done. URIs have been changed.
