### ISSUE TITLE
ROI Classes named inconsistently

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/Phaleron-SkeletalInventory#17]
Some parts in the ontology are inconsistently named.
Eg:  LeftOrbitalPartOfFrontalBone should be named OrbitalPartOfLeftFrontalBone
@15E601 for the squamous part of frontal bone, you already changed this in the ontology but forgot to change it in the implementation.
Please fix this consistently in ontology and metaphactory code.

```
[[>:PSI_SI_MD_FormTupelSnippet MyID_Comp="frontalleftorbitalcomp" MyID_Obs="frontalleftorbitalobs" ROIVar="<http://w3id.org/rdfbones/ext/phaleron-si/LeftOrbitalPartOfFrontalBone>" ]]                       
                  ,
                  [[>:PSI_SI_MD_FormTupelSnippet MyID_Comp="frontalrightorbitalcomp" MyID_Obs="frontalrightorbitalobs" ROIVar="<http://w3id.org/rdfbones/ext/phaleron-si/RightOrbitalPartOfFrontalBone>" ]]  
                  ,
                  [[>:PSI_SI_MD_FormTupelSnippet MyID_Comp="frontalleftsquamouscomp" MyID_Obs="frontalleftsquamousobs" ROIVar="<http://w3id.org/rdfbones/ext/phaleron-si/LeftSquamousPartOfFrontalBone>" ]]                       
                  ,
                  [[>:PSI_SI_MD_FormTupelSnippet MyID_Comp="frontalrightsquamouscomp" MyID_Obs="frontalrightsquamousobs" ROIVar="<http://w3id.org/rdfbones/ext/phaleron-si/RightSquamousPartOfFrontalBone>" ]]
                  ,
                  [[>:PSI_SI_MD_FormSnippet MyID="frontalfrag" MyLabel="Unsided Fragments" MinOccurs="1" MaxOccurs="1" ROIVar="<http://w3id.org/rdfbones/core#EntireBoneOrgan_fma52734>" MDClass="<http://w3id.org/rdfbones/ext/phaleron-si/NumberOfUnclassifiedFragments>" ConnectValue="obo:OBI_0001937" xsdDatatype="xsd:integer"]
```

**Comment by 15E601** [comment]
There had been some unfortunate miscommunication between me and @cuboideum - I have now uploaded the current ontology to git and will correctly document all future changes. The version on AnthroGraph has always been the most current for testing purposes. Accordingly, I find no issues on AnthroGraph; everything saves as intended for the frontal bone.

The naming convention is consistent with the FMA: fma54670 for example is labelled "Left orbital part of frontal bone". The squamous part is not split into left and right in the FMA.

With 34b7ab7cffada5d2ec0ae1c013afa89327e3b9da uploaded, does this resolve your issue?

**Comment by zarquon42b** [comment]
This fixes it. We need to purge existing SIs then to avoid confusions because that specific class is addressed differently, depending on when the SI was created.
