### ISSUE TITLE
Implementing measurement data restrictions in inventory classes

### ISSUE THREAD

**Issue by 15E601** [RDFBones/Phaleron-SkeletalInventory#2]
Inventory classes such as _phaleron-si/AdultCranium_ require restrictions that link a target bone organ class with its corresponding measurement data, these being:

### Data for fragments of bone organs

- _Number of bone fragments_ - A measurement datum giving the number of fragments from one or several bone organs.

-  _Number of unsided fragments_ - A measurement datum giving the number of fragments from a bone for which it cannot be determined to which side of the body they belong.

- _Number of unidentified fragments_ - A measurement datum giving the number of fragments from a bone for which it cannot be determined whether they belong to one given anatomical region or another, such as the petrous or the squamous part of the bone, nor to which side of the body.

- _Number of unclassified fragments_ - A measurement datum giving the number of fragments from a bone that cannot be assigned to a number of specified anatomical regions of interest defining parts of this bone.

- _Degree of skull fragmentation_	- A measurement datum assessing whether a skull is fragmented into up to 50 fragments or more.

### Data for regions of interest

- _Fifty Elements Assessment_ - A value specification that specifies whether there are up to 50 or more elements.

- _Observability_ - A value specification that specifies whether skeletal material is deemed suitable for observation in an investigation or not.

- _Taphonomic Trace_ - A value specification that specifies a taphonomic trace that is observed with a body of skeletal material.

Observability and Taphonomy use a single class for all regions of interest. Representation in 4 states, currently implemented in the test version of the adult inventory entry mask but not currently listed in the files of #1 , also uses one class for all ROIs. In contrast, every fragment measurement datum has its own class in #1 .

@zarquon42b had instructed me to implement only one class for the fragments analog to the data for ROIs. Only the unsided fragments class is currently implemented in the test version, but this issue naturally will arise with all data for fragments.

To illustrate on an arbitrary example, in the Merged_phaleron-si.owl, the frontal bone in the AdultCranium class would be restricted as follows:

![template](https://user-images.githubusercontent.com/67172847/126769659-16d0157c-54b4-417a-9d52-d8c9938a70f1.png)

Compare to the current implementation of the test version:

![implemented](https://user-images.githubusercontent.com/67172847/126769672-95c8c543-ffdd-4cf7-8226-2ed14bc1e6b8.png)

As I understand, creating a new class of fragment datum for each bone organ is redundant. It should be enough to reference the same class each time with a different bone organ as the restriction, just as is done for Representation in 4 states, Taphonomy, and Observability in the current test version.

Furthermore, the Merged_phaleron-si.owl contains measurement data that reference classes of the FMA directly, which we have decided should not be done, as all references should be to our defined ROI classes. Where do these restrictions come from, are they artifacts from earlier attempts? I am not able to find anything in the templates that would cause these restrictions to appear - I assume they are leftovers found in the input ontology files.

**Comment by cuboideum** [comment]
All measurement data are related to anatomical regions of bone organs, not to fragments of bone organs. So there should not be a distinction between 

> Data for fragments of bone organs

and

> Data for regions of interest

**Comment by cuboideum** [comment]
The measurement datum 'Degree of skull fragmentation' is too specific. It should be called 'Fifty elements assessment' to fit the value specification and the label classes.

I have created issue #3 for this task.

**Comment by cuboideum** [comment]
> Representation in 4 states, currently implemented in the test version of the adult inventory entry mask but not currently listed in the files of #1 , also uses one class for all ROIs.

This is a measurement datum class from the [implementation of the Standards Skeletal Inventory](https://github.com/RDFBones/Standards-SkeletalInventories). This extension is a requirement for the Phaleron skeletal inventory to work.

**Comment by cuboideum** [comment]
> In contrast, every fragment measurement datum has its own class in #1 .
> 
> @zarquon42b had instructed me to implement only one class for the fragments analog to the data for ROIs. Only the unsided fragments class is currently implemented in the test version, but this issue naturally will arise with all data for fragments.

Several weeks ago, we had postponed a final decision on whether measurement data on fragments should be related to anatomical regions of interest or not. The preliminary decision was not to do this. As a consequence, measurement datum classes needed to be specific to anatomical regions. At the project meeting on 19 July 2021 we reversed this preliminary decision to the effect that, now, all measurement data need to be anatomically unspecific. So the measurement data that refer to specific anatomical regions need to be eliminated and unspecific versions related to anatomical regions of interest by class restrictions.

I have created issue #5 for this task.

**Comment by cuboideum** [comment]
> Furthermore, the Merged_phaleron-si.owl contains measurement data that reference classes of the FMA directly, which we have decided should not be done, as all references should be to our defined ROI classes.

This is a bug. Please open a separate issue specifying the concrete measurement data.

**Comment by cuboideum** [comment]
@15E601: Please close issue once all questions are answered or deferred to separate issues.

**Comment by 15E601** [comment]
All questions are answered or have received their own issue.
