### ISSUE TITLE
Create sorting relations to improve tabular dataset output

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/Phaleron-SkeletalInventory#22]
Issue https://github.com/RDFBones/RDFBonesPhaleron/issues/62 requests a sorting mechanism for the tabular output of the skeletal inventory.

**Comment by cuboideum** [comment]
In a discussion today, @zarquon42b and I decided that sorting should be organised as follows:

* Relations between the dataset class and the dataset section classes define the order of dataset sections
* Relations between the dataset section classes and the anatomical regions of interest define the order of ROIs within the sections

Alternatively, sorting of measurement data could be implemented in the restrictions on the dataset section classes that define the measurement data contained by the sections. Relationships to ROIs, however, are easier to query.

**Comment by 15E601** [comment]
Since this is a mirror of https://github.com/RDFBones/RDFBonesPhaleron/issues/62 and the solution mentioned in this issue has even been implemented, I find it makes sense to close this issue and keep the discussion in the "main" issue. I see no reason to have the same issue open twice.
