### ISSUE TITLE
Rename "Degree of skull representation"

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/Phaleron-SkeletalInventory#3]
The files provided in #1 contain the measurement datum "Degree of skull representation".

The measurement datum should be renamed to "Fifty elements assessment" to match the existing value specification and category label classes. Instances can be linked to "Entire skull" or other anatomical regions of interest as desired.

**Comment by 15E601** [comment]
Which values can this datum take? Below 51 fragments will it receive the number of fragments, and above simply say >50? Or is a simple true/false value? There appears to be some overlap in functionality with NumberOfBoneFragments.

Is the fifty elements assessment still restricted to the cranium? If not, then for the rdfs:label I propose "Value of fifty elements assessment".

**Comment by cuboideum** [comment]
> Which values can this datum take?

This is already specified in the templates for value specifications and categorical labels.

The basis for these specifications is the following passage from page 4 of the Inventory Scoring Key:

> When recording grouped skeletal elements, a number of fragments/elements from that grouped region of the skeletal is recorded as opposed to using a completeness score. The exceptions to this rule are the "Skull grouped" and “Misc Fragments” sections in which you will select one of two options (e.g., "Skull grouped" are "<50" or ">50").

The templates resolve the logical problem that the exact value 50 is not covered. This followed a conversation with Jane and Eleanna.

You can find the scoring key on the OwnCloud.

**Comment by 15E601** [comment]
The datum has been renamed.
