### ISSUE TITLE
Unclear hierarchy and ontology interaction in classes for segments of bone organs

### ISSUE THREAD

**Issue by 15E601** [RDFBones/Phaleron-SkeletalInventory#4]
The preliminary template for anatomical ROIs provided in issue #1 contains the parent classes of e.g. "SegmentOfFirstLeftRib". The vertebrae classes do not have these classes in the template; only "SegmentOfSupernumeraryThoracicVertebra" and "SegmentOfSupernumeraryLumbarVertebra" exist. All classes of this type not present in the template are instead inferred by referencing them as a parent class

This discrepancy is accordingly reflected in the Phaleron-si ontology produced by the process, i.e. Merged_phaleron-si.owl in #1: all rib classes are organised as a subclass of "SegmentOfRib", which itself is a subclass of "SegmentOfBoneOrgan". All vertebrae classes are stand-alone classes (by which I mean the higher-level class "SegmentOfSecondLumbarVertebra" itself and along with it its subclasses of the body, left neural arch, and right neural arch) when they should instead be subclasses of "SegmentOfVertebra", which in turn should also be a subclass of "SegmentOfBoneOrgan".

This has implications for issue #2: The current implementation of the Phaleron-si.owl makes use of both the initial "SegmentOf" classes as a reference for the "NumberOfUnsidedFragments" measurement datum (e.g. "SegmentOfFifthThoracicVertebra" would be the reference class for the datum of the number of unsided fragments of the 5th thoracic vertebra). In cases where such a "SegmentOf" class did not yet exist, the FMA classes where erroneously used instead.

I have attempted to correct this in the current expanded version of the anatomical ROI template I am working on (not yet uploaded anywhere) by including 3 classes for the ilium:

**phaleron-si:Ilium** - This anatomical region of interest describes the same bone as the FMA class 'Ilium' (fma:16589).  - This is a subclass of standards-si:SegmentOfIlium

**phaleron-si:LeftIlium** - This anatomical region of interest describes the same zone of an ilium bone as the FMA class 'Left ilium' (fma:16591).  - This is a subclass of phaleron-si:Ilium

**phaleron-si:RightIlium**  - This anatomical region of interest describes the same zone of an ilium as the FMA class 'Right ilium' (fma:16590).  - This is a subclass of phaleron-si:Ilium

Here I planned to use "phaleron-si:Ilium" as the reference for the unsided fragments datum. However, this would be at odds with already established classes like the ribs, where the ROIs (e.g. "BodyOfEighthRib") are a direct subclass of a "SegmentOf" class (e.g. "SegmentOfEighthRib" in this case respectively). There should instead be an intermediate class of "phaleron-si:EighthRib" or some such to which the unsided fragment datum would be attached. Strictly speaking, the ilium is also not a ROI in the tabular inventory sheets of the Phaleron work group - the left and right segments of the ilium are the actual ROIs, together with the unsided fragments.

The alternative is to cut the phaleron-si:Ilium class and have the left and right ROIs of the ilium be direct subclasses of standards-si:SegmentOfIlium, analogous the current method for ribs and vertebrae.

This leaves me with the following questions:

1.  Why is "SegmentOfRib", a very high-level class, not a part of the standards-si ontology? Why is "SegmentOfFifthThoracicVertebra", a class more specific than "SegmentOfRib", explicitly put into the standards-si ontology?

2. Is it possible and/or desired to have the expected hierarchy for the vertebrae classes preserved in the produced Merged_phaleron.si.owl?

3. Which method is preferred for the measurement data that must be attached to a "higher-level" ROI like number of unsided fragments and number of unclassified fragments, which would not be attached to the lowest-level ROIs, which (for most bones) have a left and right differentiation?

**Comment by cuboideum** [comment]
Answer to question 1:
> Why is "SegmentOfRib", a very high-level class, not a part of the standards-si ontology? Why is SegmentOfFifthThoracicVertebra", a class more specific than "SegmentOfRib", explicitly put into the standards-si ontology?

The extension [Standards - SkeletalInventories](https://github.com/RDFBones/Standards-SkeletalInventories) is a requirement for the extension [Phaleron - SkeletalInventory](https://github.com/RDFBones/Phaleron-SkeletalInventory). As a consequence, the Phaleron extension actually not just extends the [RDFBones core ontology](https://github.com/RDFBones/RDFBones-O) but a graph that is merged from the core ontology and the Standards extension. The Standards only score entire ribs. Therefore, a class "SegmentOfRib" would have been without subclasses. As the Phaleron extension scores different segments of ribs, the class "SegmentOfRib" is introduced here.

The Phaleron extension does not take the Standards extension as a requirement because it is on a higher hierarchical level but because that extension (and the standard it implements) was already in existence when the Phaleron standard was created.

**Comment by cuboideum** [comment]
Answer to question 2:

> Is it possible and/or desired to have the expected hierarchy for the vertebrae classes preserved in the produced Merged_phaleron.si.owl?

I am not quite sure what is meant by the question. The Standards extension aims for a meaningful hierarchy of anatomical regions of interest in a graph that merges the core ontology and the Standards extension. The Phaleron extension aims for a meaningful hierarchy of anatomical regions of interest in a graph that merges the core ontology, the Standards extension and the Phaleron extension. This is because the Phaleron extension takes the Standards extension as a requirement.

Does this answer the question?

**Comment by cuboideum** [comment]
Answer to question 3:

> Which method is preferred for the measurement data that must be attached to a "higher-level" ROI like number of unsided fragments and number of unclassified fragments, which would not be attached to the lowest-level ROIs, which (for most bones) have a left and right differentiation?

The question is to what super-class level of anatomical regions of interest measurement data are to be related, right? This depends on what needs to be counted in every specific case.

Measurement data about unsided fragments are referred to classes representing anatomical regions of interest that typically have two sub-classes (for the right and left elements). Measurement data about unclassified fragments have a higher degree of uncertainty, not just concerning body side but also the differentiation of anatomical regions of interest on a bone organ. Ultimately they might be referred to an anatomical region of interest describing an entire bone organ.

**Comment by cuboideum** [comment]
> phaleron-si:Ilium - This anatomical region of interest describes the same bone as the FMA class 'Ilium' (fma:16589).

This is not needed because the class standards-si:Ilium already exists. Its definition is the following:

> This anatomical region of interest describes the same segment of a bone organ as the FMA class 'Ilium' (fma:16589). - This is a subclass of standards-si:SegmentOfIlium

Note that this formulation follows FMA nomenclature as class fma:16589 is modelled as a sub-class of 'Segment of hip bone' (fma:327641). Consequently, the super-class of standards-si:Ilium is called standards-si:SegmentOfHipBone.

As the Phaleron - Skeletal Inventory extension has the Standards - Skeletal Inventory extension as a requirement it should re-use the Standards classes wherever possible.

**Comment by cuboideum** [comment]
> However, this would be at odds with already established classes like the ribs, where the ROIs (e.g. "BodyOfEighthRib") are a direct subclass of a "SegmentOf" class (e.g. "SegmentOfEighthRib" in this case respectively). There should instead be an intermediate class of "phaleron-si:EighthRib" or some such to which the unsided fragment datum would be attached. Strictly speaking, the ilium is also not a ROI in the tabular inventory sheets of the Phaleron work group - the left and right segments of the ilium are the actual ROIs, together with the unsided fragments.

I do not quite understand the part about what the ilium is in the Phaleron inventory sheets. But the class that is perceived as missing would be rdfbones:EntireEighthRib.

**Comment by 15E601** [comment]
> Answer to question 2:
> 
> > Is it possible and/or desired to have the expected hierarchy for the vertebrae classes preserved in the produced Merged_phaleron.si.owl?
> 
> I am not quite sure what is meant by the question. The Standards extension aims for a meaningful hierarchy of anatomical regions of interest in a graph that merges the core ontology and the Standards extension. The Phaleron extension aims for a meaningful hierarchy of anatomical regions of interest in a graph that merges the core ontology, the Standards extension and the Phaleron extension. This is because the Phaleron extension takes the Standards extension as a requirement.
> 
> Does this answer the question?

The standards ontology has a functioning hierarchy
![standards_ordered](https://user-images.githubusercontent.com/67172847/127159059-c31a264b-1e3a-4969-b5b6-5d599e7ce200.png)

While this hierarchy is lost in the merged phaleron ontology
![phaleron_merged](https://user-images.githubusercontent.com/67172847/127159071-b6653b47-5ce6-47ea-848c-31a2c1caece8.png)

**Comment by cuboideum** [comment]
> The standards ontology has a functioning hierarchy
standards_ordered
> 
> While this hierarchy is lost in the merged phaleron ontology
phaleron_merged

This is because the Phaleron needs to be merged with the core ontology and the Standards extension to become fully functional.

**Comment by 15E601** [comment]
> > phaleron-si:Ilium - This anatomical region of interest describes the same bone as the FMA class 'Ilium' (fma:16589).
> 
> This is not needed because the class standards-si:Ilium already exists. Its definition is the following:
> 
> > This anatomical region of interest describes the same segment of a bone organ as the FMA class 'Ilium' (fma:16589). - This is a subclass of standards-si:SegmentOfIlium
> 
> Note that this formulation follows FMA nomenclature as class fma:16589 is modelled as a sub-class of 'Segment of hip bone' (fma:327641). Consequently, the super-class of standards-si:Ilium is called standards-si:SegmentOfHipBone.
> 
> As the Phaleron - Skeletal Inventory extension has the Standards - Skeletal Inventory extension as a requirement it should re-use the Standards classes wherever possible.

In the current merged phaleron-si there are already a number of classes from the standards-si included;

> This is because the Phaleron needs to be merged with the core ontology and the Standards extension to become fully functional.

-> From this I gather there is another step that comes after the steps mentioned in issue #1 where the phaleron and standards ontologies are fully integrated. I assume all the standards classes found in the Merged_phaleron-si come from the "parent class" column of the anatomical ROI template. This means, if I understand this correctly, that no action is necessary _in the anatomical ROI template_ for the ilium classes and all other classes already appropriately represented for the phaleron-si in the standards-si.

**Comment by cuboideum** [comment]
> In the current merged phaleron-si there are already a number of classes from the standards-si included

The standards-si classes referenced in the templates (e.g. in the 'parent class' columns) should appear in the phaleron-si OWL file. But they should only be named. Class definitions, editor notes and other annotations should not be included.

**Comment by cuboideum** [comment]
The phaleron-si extension is intended to be loaded into a system that already has both the core ontology and the standards-si extension loaded.

> This means, if I understand this correctly, that no action is necessary in the anatomical ROI template for the ilium classes and all other classes already appropriately represented for the phaleron-si in the standards-si.

This should be correct (except that there might well be mistakes that need correction).

**Comment by cuboideum** [comment]
> From this I gather there is another step that comes after the steps mentioned in issue #1 where the phaleron and standards ontologies are fully integrated.

This step comes at the end when the new extension is loaded together with the core ontology and the existing extension.

Issue #1 provides the file 'RDFBonesCoreStandardsSI.owl' that merges the core ontology and the standards-si extension. This is needed by ROBOT to look up class labels and IDs. To see if the phaleron-si extension works as expected it has to be merged with this file. The result should be a coherent ontology.

**Comment by cuboideum** [comment]
Issue #1 is missing a list of core ontology and standards-si classes that are needed for reference in phaleron-si class restrictions. When I began developing phaleron-si, I started such a list. Later I gave it up to save time. Now, unfortunately, the ideas about what ROIs are needed are exclusively in my mind and they need to be recreated while defining class restrictions.

**Comment by 15E601** [comment]
> Issue #1 is missing a list of core ontology and standards-si classes that are needed for reference in phaleron-si class restrictions. When I began developing phaleron-si, I started such a list. Later I gave it up to save time. Now, unfortunately, the ideas about what ROIs are needed are exclusively in my mind and they need to be recreated while defining class restrictions.

As I understand, the next job for me is to figure out which classes can be taken from the standards-si and which need to be newly made for phaleron-si in the template file, lest we end up with duplicates (as is already starting to be the case). Do you still have the incomplete list, or shall I start from scratch?

**Comment by 15E601** [comment]
Some bones are stand-alone and do not fit the schema of "SegmentOfBoneOrgan" that the vast majority of classes adheres to in the phaleron-si; the vomer and ethmoid, for example, are not divided into segments like the sphenoid and frontal bones. Inserting them as a subclass of SegmentOfBoneOrgan would only make sense if SegmentOfCranium were a subclass of SegmentOfBoneOrgan in the standards-si, but the cranium as a whole, I think, does not qualify as a bone organ. What should I enter as parent class for these types of bones?

**Comment by cuboideum** [comment]
> As I understand, the next job for me is to figure out which classes can be taken from the standards-si and which need to be newly made for phaleron-si in the template file, lest we end up with duplicates (as is already starting to be the case). Do you still have the incomplete list, or shall I start from scratch?

My lists were actually ROBOT extract scripts. In the beginning I was not sure if the extracted classes might come in handy. In the meantime, we have decided not to include imported classes in the extensions. These are the latest versions of the files:

[phaleron-si-ImportScripts.zip](https://github.com/RDFBones/Phaleron-SkeletalInventory/files/6893011/phaleron-si-ImportScripts.zip)

**Comment by cuboideum** [comment]
> Some bones are stand-alone and do not fit the schema of "SegmentOfBoneOrgan" that the vast majority of classes adheres to in the phaleron-si; the vomer and ethmoid, for example, are not divided into segments like the sphenoid and frontal bones. Inserting them as a subclass of SegmentOfBoneOrgan would only make sense if SegmentOfCranium were a subclass of SegmentOfBoneOrgan in the standards-si, but the cranium as a whole, I think, does not qualify as a bone organ. What should I enter as parent class for these types of bones?

The "stand-alone bones" are actually those bone organs that are scored in their entirety. The relevant anatomical regions of interest are already in the core ontology, as sub-classes of class 'Entire bone organ' (rdfbones:EntireBoneOrgan).

Fragments of the skull is a difficult one. The anatomical region of interest still needs to be created. It has to be a subclass of class 'Combination of skeletal segments' (rdfbones:CombinationOfSkeletalSegments) and as regional parts it has all sub-classes of the 'Entire bone organ' class that refer to elements of the skull.

**Comment by 15E601** [comment]
So what of the individual carpal bones, then? Should they be considered subclasses of "EntireBoneOrgan_fma23889", while the metacarpals would be subclasses of "EntireBoneOrgan_fma9612"?

I find this nomenclature confusing. The definition of the "bone organ" class in the FMA sounds as though it would consider these two parent classes _a combination of_ bone organs. The only exception I see is the hip bone, fma16585, but I can see why it is added, since all bone organs involved are expected to fuse in adults. The same can not be said of the metacarpals or metatarsals. Is this based on the definitions of Buikstra & Ubelaker rather than the FMA?

**Comment by cuboideum** [comment]
> So what of the individual carpal bones, then? Should they be considered subclasses of "EntireBoneOrgan_fma23889", while the metacarpals would be subclasses of "EntireBoneOrgan_fma9612"?

Yes, this is true for the anatomical regions representing specific carpal bones or metacarpal bones.

**Comment by cuboideum** [comment]
> The definition of the "bone organ" class in the FMA sounds as though it would consider these two parent classes a combination of bone organs.

Why would 'Entire carpal bone' or 'Entire metacarpal bone' represent combinations of bone organs?

**Comment by 15E601** [comment]
> Why would 'Entire carpal bone' or 'Entire metacarpal bone' represent combinations of bone organs?

To be clear, I am not saying the definition is wrong, just that I have trouble understanding it. I can try to clarify my point of view:
There is no such thing as an entire metacarpal bone. There is an arbitrarily defined area of the hand that consists only of the individual metacarpals, which themselves are bone organs in the true sense, as they are a self-contained unit. They have a true physical boundary that coincides completely with the material of the bone. The "Entire metacarpal bone" is not a self-contained unit, it is imaginary and consists of multiple bones. It is as much a bone organ as is the hypothetical class "entire arm bone".

**Comment by cuboideum** [comment]
This is the problem that we discussed during the project meeting. The sub-classes of class 'Entire metacarpal bone' are not parts of this entire metacarpal bone but each of them is an entire metacarpal bone. The super-class can replace any of the sub-classes which are just more specific versions of the superordinate concept.

If we talk about an 'entire metacarpal bone' we are talking about the entirety of **one** bone organ that is either a first or a second or a third or a fourth or a fifth metacarpal bone. If we talk about an 'entire first metacarpal bone' we are talking about the entirety of **one** bone organ that is either a left first metacarpal bone or a right first metacarpal bone. An 'entire left first metacarpal bone' is **also** an 'entire first metarcarpal bone' and **also** an 'entire metacarpal bone'.

Does this help?

What constitutes a bone organ is sometimes problematic. The hip bone fuses from three components that are separated during childhood. Each long bone starts off as three components, diaphysis and two epiphyses, which only fuse after the end of the growth period. Cranial sutures fuse in early adulthood. Still, the hip bone and long bones are addressed as bone organs while the neurocranium is not considered a bone organ but a structure formed by several bone organs. These definitions we leave to the FMA to decide. We just go by their understanding of what is to be understood as bone organ.
