### ISSUE TITLE
Make measurement data about fragments unspecific

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/Phaleron-SkeletalInventory#5]
The resources provided in issue #1 contain measurement data about numbers of unclassified fragments that are specific to certain anatomical regions of interest. This goes back to a preliminary design decision that is no longer relevant (cf. [comment](https://github.com/RDFBones/Phaleron-SkeletalInventory/issues/2#issuecomment-887443515) for issue #2).

These need to be replaced by unspecific measurement data as listed in issue #2:

>  * Number of bone fragments - A measurement datum giving the number of fragments from one or several bone organs.
> 
> * Number of unsided fragments - A measurement datum giving the number of fragments from a bone for which it cannot be determined to which side of the body they belong.
>
> * Number of unidentified fragments - A measurement datum giving the number of fragments from a bone for which it cannot be determined whether they belong to one given anatomical region or another, such as the petrous or the squamous part of the bone, nor to which side of the body.
> 
> * Number of unclassified fragments - A measurement datum giving the number of fragments from a bone that cannot be assigned to a number of specified anatomical regions of interest defining parts of this bone.

The unspecific measurement data are linked to anatomical regions of interest through class restrictions.

**Comment by cuboideum** [comment]
I would suggest to model the measurement data in a subclass hierarchy. And to improve on my initial class definitions.

* _Number of bone fragments_ - A measurement datum giving the number of fragments from one or several bone organs.
     * _Number of unclassified fragments_ - A measurement datum giving the number of bone fragments that cannot be assigned to one of a number of specified anatomical regions of interest.
          * _Number of unsided fragments_ - A measurement datum giving the number of bone fragments belonging to a certain type of anatomical region of interest for which it cannot be determined to which side of the body they belong.

The re-formulation of the class definitions intends to make the measurement data applicable to anatomical regions of interest that comprise several bone organs.

I think we can drop the class 'Number of unidentified fragments' as it seems to mean the same as 'Number of unclassified fragments'. Or am I missing something?

**Comment by 15E601** [comment]
An unclassified fragment can be sided, unlike an unidentified fragment, which can be neither sided nor classified.

**Comment by 15E601** [comment]
The measurement data have now been made unspecific. Unclassified fragments are only recorded in the "unsided fragments" column of "grouped" rows (cf inventory key) where "The term "grouped" is used to inventory elements that are unsided and/or undifferentiated". To my understanding, the inventory key does not allow for instances where a fragment is both sided and undifferentiated.
