### ISSUE TITLE
Direct references to classes of the FMA in the Merged_phaleron-si ontology

### ISSUE THREAD

**Issue by 15E601** [RDFBones/Phaleron-SkeletalInventory#6]
As mentioned in issue #2 , there are unintended references to FMA classes in the restrictions of the cranium inventory class in the Merged_phaleron-si.owl. For example, the following snippet can be found among the cranium restrictions:

![fma_artifact](https://user-images.githubusercontent.com/67172847/127187899-3b9cc241-184f-44bb-920c-9f3d1280e1b9.png)

I assume this comes from the data item restrictions found in the template of the skeletal inventory sections. Here there is, among many other FMA classes, Manchester syntax for the observability of the Petrous part of the right temporal bone, which fma52875 represents.

My solution would be to simply delete the current Manchester syntax in the sections template and replace it with the correct restrictions, as there is not much of it and most of it does not adhere to our current rules.

**Comment by cuboideum** [comment]
> My solution would be to simply delete the current Manchester syntax in the sections template and replace it with the correct restrictions, as there is not much of it and most of it does not adhere to our current rules.

Yes, this is the correct way to proceed.
