### ISSUE TITLE
Unclear regions of interest in scoring tables

### ISSUE THREAD

**Issue by 15E601** [RDFBones/Phaleron-SkeletalInventory#7]
The existence of ROIs is presented through the use of various shades of grey in the tabular scoring files - while it is possible to deduce what might be meant, overall the shading does not follow a specific scheme. The anatomical ROI template for the ROBOT script offers clarity for some ROIs, but not all. The scoring files also have a tendency to cut corners, e.g. sometimes including an explicit "grouped" row, and sometimes not.

I propose the following ROIs, highlighted in magenta, and _**only in magenta**_. Note that for simplicity's sake I am here referring to the unsided fragments column also as a region of interest.

![roi_highlighting](https://user-images.githubusercontent.com/67172847/127479234-fecf835c-2977-4c5b-bf90-1ffb55870d89.png)

Note, also, that the exact use of measurement data of those in issue #5 other than unsided fragments are very poorly communicated in the scoring files as well.

Some nomenclature conflicts also exist between the standards-si and the tables, such as the use of "epiphysis" in the ontology versus "articulation" in the tables for ROIs of the long bones (for reference, Jane has confirmed that these are synonymous in this instance). The clavicle section notes the ROIs "Medial artic" and "Scap artic"; while these obviously note the two epiphyses of the clavicle in some way, to which region of the FMA ontology exactly these would relate is not clear. This also poses the question if the search for a corresponding FMA class is required for every newly created phaleron-si class.

**Comment by cuboideum** [comment]
The most current version of the inventory template that we have is the following:

"~/ownCloud/DFG-Standards/DFG-SemanticResearchDataModelling/Phaleron_Bioarchaeological_Project/Forms_and_Protocols/Inventory/Inventory Template Updated 4.8.21-Download-2021-06-04.xlsx"

Following this version, I would suggest that the following fields in your table should also be tinted in magenta:

* Frontal, Pars Orbitalis - #Unsided frag.
* Temporal, Pars Squama - #Unsided frag.
* Temporal, Pars Petrosa - #Unsided frag.

Otherwise, I would follow your interpretation.

**Comment by 15E601** [comment]
Yes, you're right, pars squama and petrosa need to be viewed seperately. I will move these away from the grouped ROI, as otherwise the possibility exists that fragments for regions like the orbitalis are counted twice. This makes the following table for the entire cranium:
![roi_highlighting_expanded](https://user-images.githubusercontent.com/67172847/127486313-5db1bc25-a92b-4108-bcd8-58cb656be084.png)

**Comment by cuboideum** [comment]
> The clavicle section notes the ROIs "Medial artic" and "Scap artic"; while these obviously note the two epiphyses of the clavicle in some way, to which region of the FMA ontology exactly these would relate is not clear.

This is also not exactly necessary as our 'Segments of bone organ' only reference the bone organ they derive from. I have taken the habit to reference the equivalent FMA element in the editor notes.

> This also poses the question if the search for a corresponding FMA class is required for every newly created phaleron-si class.

No and yes, as explained above. I think it is a good idea to reference equivalent classes as this prevents misunderstandings in the future.

**Comment by 15E601** [comment]
> This makes the following table for the entire cranium

Mistake: if a fragment qualifies as unclassified, that means it can be sided. If it can be sided, that means it isn't part of the squama, which means it's part of the orbitalis, which means it isn't unclassified. It is difficult for me to judge where unclassified fragments may actually occur - is it possible a fragment may be sided as "middle", but it is not clear if it belongs to the squama or basilaris of the occipital? Unlikely, I'd assume.

**Comment by 15E601** [comment]
Why do we have "LeftSideOfMandible" and "RightSideOfMandible" on the one hand, and "EntireBoneOrgan_fma53650" and "EntireBoneOrgan_fma53649" on the other? Does the mandible stem from a single unit in ontogeny while the maxilla has 2?

**Comment by cuboideum** [comment]
> Does the mandible stem from a single unit in ontogeny while the maxilla has 2?

Yes. That is why the FMA lists left and right maxilla as two separate bone organs and the entire mandible as one. And, as always, we follow the FMA.

**Comment by 15E601** [comment]
Is "standards-si/AuricularSurfaceOfIlium" acceptable as the reference class for the Phaleron ROI "Auricular Region (including post auric)" or shall I create a new class "phaleron-si/AuricularAndPostAuricRegion"? Shall this new class still reference fma:16935?

**Comment by 15E601** [comment]
What do rows like "Scapula, grouped" under the scapula section expect for their cells? I assume they exist only for unsided fragments, as unclassified fragments are not explicitly mentioned here. However, the entire line is marked in dark grey. I assume only the final cell under unsided fragments is expected to receive a value, and that value being the total of fragments across all segments of scapula. 

![scapula_fragments](https://user-images.githubusercontent.com/67172847/127525479-be1e6eb8-460c-4d99-9f53-f66b2f861eb5.png)

However, if there were a cell in which to put a value for unclassified fragments - as we have discussed outside these issues, this would now take on the definition of "fragments that can be not be attributed to a specific region of a bone organ in any discernible way" - this would be that cell. I assume this latter option **_is not_** what is meant.

**Comment by cuboideum** [comment]
> Is "standards-si/AuricularSurfaceOfIlium" acceptable as the reference class for the Phaleron ROI "Auricular Region (including post auric)" or shall I create a new class "phaleron-si/AuricularAndPostAuricRegion"? Shall this new class still reference fma:16935?

I have moved this to the new issue #8.

**Comment by cuboideum** [comment]
> What do rows like "Scapula, grouped" under the scapula section expect for their cells? I assume they exist only for unsided fragments, as unclassified fragments are not explicitly mentioned here. However, the entire line is marked in dark grey. I assume only the final cell under unsided fragments is expected to receive a value, and that value being the total of fragments across all segments of scapula.

I do not know the answer. It might make sense to enter values in the cells you have marked with NO VALUE:

* Scapula, grouped / Left: 'Number of unclassified fragments' about 'Entire left scapula'
* Scapula, grouped / Right: 'Number of unclassified fragments' about 'Entire right scapula'
* Scapula, grouped / #Unsided frag.: 'Number of unclassified fragments' about 'Entire scapula'

Here, these fields take the numbers of fragments that can be assigned to a body side but not to any of the defined regions of the scapula. I do not know if this case occurs frequently. Ultimately, only Jane and Eleanna can tell.

**Comment by cuboideum** [comment]
> However, if there were a cell in which to put a value for unclassified fragments - as we have discussed outside these issues, this would now take on the definition of "fragments that can be not be attributed to a specific region of a bone organ in any discernible way" - this would be that cell. I assume this latter option **_is not_** what is meant.

This I do not understand. What is the current definition of 'Number of unclassified fragments'?

**Comment by 15E601** [comment]
> This I do not understand. What is the current definition of 'Number of unclassified fragments'?

Well, unclassified means whatever you decide it means. In the definition given by issue #5, I understand this to mean the bone fragment can be assigned to a bone organ, but not to a ROI of the bone organ, yes? "A measurement datum giving the number of bone fragments that cannot be assigned to one of a number of specified anatomical regions of interest." I then thought we could expand this to also mean that the fragment can not be sided, as you suggested to drop the "unidentified fragment" datum due to 'uselessness', which would make sense, as there are very few cases where a fragment can be sided, but not attributed to a ROI, I imagine.
I think utlimately we will have to compile all unclear fields and ask the Phaleron group.

**Comment by cuboideum** [comment]
I have turned https://github.com/RDFBones/Phaleron-SkeletalInventory/issues/7#issuecomment-889690651 into the new issue #9.

**Comment by 15E601** [comment]
For the moment, all ROIs seem clear.
