### ISSUE TITLE
phaleron-si:NumberOfUnclassifiedFragments

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/Phaleron-SkeletalInventory#9]
> This I do not understand. What is the current definition of 'Number of unclassified fragments'?

Well, unclassified means whatever you decide it means. In the definition given by issue #5, I understand this to mean the bone fragment can be assigned to a bone organ, but not to a ROI of the bone organ, yes? "A measurement datum giving the number of bone fragments that cannot be assigned to one of a number of specified anatomical regions of interest." I then thought we could expand this to also mean that the fragment can not be sided, as you suggested to drop the "unidentified fragment" datum due to 'uselessness', which would make sense, as there are very few cases where a fragment can be sided, but not attributed to a ROI, I imagine.
I think utlimately we will have to compile all unclear fields and ask the Phaleron group.

_Originally posted by @15E601 in https://github.com/RDFBones/Phaleron-SkeletalInventory/issues/7#issuecomment-889690651_

**Comment by cuboideum** [comment]
> "A measurement datum giving the number of bone fragments that cannot be assigned to one of a number of specified anatomical regions of interest."

Yes, I would go with this definition.

I do not think it is necessary to include unsidedness in the definition. The measurement datum will be about some anatomical region of interest and this reference will define whether it is an issue or not. If it is about 'Entire left parietal bone' it is not, if about 'Entire parietal bone' it is.

**Comment by cuboideum** [comment]
> Well, unclassified means whatever you decide it means.

You are responsible for the seketel inventory extension now. So beforehand, you decide.

**Comment by 15E601** [comment]
To the functionality of the inventory, a differentiation between unsided and unclassified does not seem necessary to me. As mentioned in issue #5, there is no case in which an unclassified fragment is not also unsided, and each time a different ROI-class is referenced. It would be possible to have the entire inventory only record the datum "unclassifed fragments" and have it subsume the definitions of both unsided and unclassified fragments.
I have nonetheless implemented a differentiation where unsided fragments are always classified/differentiated. If they are both unsided and undifferentiated, they count as unclassified. This type of datum can only be found in the "unsided fragments" column of each "grouped" row.

**Comment by 15E601** [comment]
Unsided Fragments has been removed as a category. Fragments are either simply bone fragments when sided and differentiated, or unclassified fragments. Unclassified fragments can be unsided, undifferentiated, or both.
